#version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - devops
    restart: always
#    healthcheck:
#        test: [ “CMD”, “mysqladmin”, “ping”, “-h”, “localhost”, “-uroot”, “-proot” ]
#        interval: 10s
#        timeout: 5s
#        retries: 5
#        start_period: 60s

  backend:
    container_name: backend
    image: rupesh1997/backend:1.0.0
    ports:
      - "9191:9191"
    networks:
      - devops
    depends_on:
      - mysql
    restart: always

  frontend:
    container_name: frontend
    image: rupesh1997/frontend:1.0.0
    ports:
      - "8080:80"
    networks:
      - devops
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
    driver: local

networks:
  devops:
    driver: bridge