kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
  namespace: kubernetes-live
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191