kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  labels:
    app: frontend
  namespace: kubernetes-live

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rupesh1997/frontend:latest
          ports:
            - containerPort: 80