kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  labels:
    app: frontend
  namespace: kubernetes-live
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80